#!/usr/bin/env python3

import argparse


def import_bench(
    name=None, branch=None, commit=None, date=None, normal_file=None,
    json_file=None, **kwargs
):
    print(kwargs)


def main():
    parser = argparse.ArgumentParser()
    subparsers = parser.add_subparsers(required=True, dest="method")
    import_parser = subparsers.add_parser(
        "import", help="import benchmark results")
    import_parser.add_argument("--name", help="benchmark name", required=True)
    import_parser.add_argument("--branch", help="branch name", required=True)
    import_parser.add_argument("--commit", help="commit sha", required=True)
    import_parser.add_argument("--date", help="date", required=True)
    import_parser.add_argument("normal_file", help="fio normal output file")
    import_parser.add_argument("json_file", help="fio json output file")
    args = parser.parse_args()
    if args.method == "import":
        import_bench(**vars(args))


if __name__ == '__main__':
    main()
